"""add store_id to sales

Revision ID: 463145ae71b7
Revises: 5526b8862a9d
Create Date: 2025-08-20 18:43:00.774154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463145ae71b7'
down_revision: Union[str, None] = '5526b8862a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'store_id')
    # ### end Alembic commands ###
