"""Add user tracking and audit fields

Revision ID: c3831e6bcdc7
Revises: f7f8e6dd57a8
Create Date: 2025-08-24 13:26:30.096488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3831e6bcdc7'
down_revision: Union[str, None] = 'f7f8e6dd57a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    #op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    #op.add_column('products', sa.Column('created_by', sa.Integer(), nullable=False))
    #op.add_column('products', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.alter_column('products', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('products', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'])
    op.add_column('sales', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('sales', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('sales', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('sales', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'])
    op.add_column('stores', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('stores', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stores', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('stores', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.drop_index('name', table_name='stores')
    op.create_foreign_key(None, 'stores', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'stores', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_index('name', 'stores', ['name'], unique=True)
    op.drop_column('stores', 'updated_by')
    op.drop_column('stores', 'created_by')
    op.drop_column('stores', 'updated_at')
    op.drop_column('stores', 'created_at')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.alter_column('sales', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sales', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('sales', 'product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('sales', 'user_id')
    op.drop_column('sales', 'updated_at')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'store_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('products', 'stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
